[pytest]
DJANGO_SETTINGS_MODULE = config.settings.test
python_files = tests.py test_*.py *_tests.py
testpaths = tests apps/core/tests apps/authentication/tests apps/users/tests apps/institutions/tests apps/academic/tests apps/audit/tests apps/notifications/tests apps/certificates/tests apps/students/tests apps/staff/tests apps/dashboard/tests apps/governance/tests apps/finance/tests apps/admissions/tests
addopts = -ra --strict-markers
