# Generated by Django 5.2 on 2026-05-28 21:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0001_initial"),
        ("colleges", "0001_initial"),
        ("notifications", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="notification",
            name="action_url",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="notification",
            name="category",
            field=models.CharField(
                choices=[
                    ("academic", "Academic"),
                    ("finance", "Finance"),
                    ("exam", "Exam"),
                    ("admission", "Admission"),
                    ("general", "General"),
                    ("attendance", "Attendance"),
                    ("certificate", "Certificate"),
                    ("placement", "Placement"),
                    ("hostel", "Hostel"),
                ],
                default="general",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="notification",
            name="send_whatsapp",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="usernotification",
            name="channels_sent",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="usernotification",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("ANNOUNCEMENT", "Announcement"),
                    ("EVENT", "Event"),
                    ("EXAM", "Exam"),
                    ("FEE", "Fee"),
                    ("ATTENDANCE", "Attendance"),
                    ("ASSIGNMENT", "Assignment"),
                    ("RESULT", "Result"),
                    ("EMERGENCY", "Emergency"),
                    ("GENERAL", "General"),
                    ("INFO", "Info"),
                    ("SUCCESS", "Success"),
                    ("WARNING", "Warning"),
                    ("ERROR", "Error"),
                    ("ALERT", "Alert"),
                ],
                default="GENERAL",
                max_length=15,
            ),
        ),
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("attachment", models.CharField(blank=True, max_length=500)),
                (
                    "announcement_type",
                    models.CharField(
                        choices=[
                            ("general", "General"),
                            ("urgent", "Urgent"),
                            ("academic", "Academic"),
                            ("exam", "Exam"),
                            ("placement", "Placement"),
                            ("hostel", "Hostel"),
                            ("event", "Event"),
                            ("holiday", "Holiday"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                (
                    "target_audience",
                    models.CharField(
                        choices=[
                            ("all", "All"),
                            ("students", "Students"),
                            ("staff", "Staff"),
                            ("specific_dept", "Specific Department"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                ("is_pinned", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="colleges.college",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="announcements",
                        to="notifications.notification",
                    ),
                ),
                (
                    "published_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="announcements_published",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "target_departments",
                    models.ManyToManyField(
                        blank=True,
                        related_name="announcements",
                        to="colleges.department",
                    ),
                ),
                (
                    "target_programs",
                    models.ManyToManyField(
                        blank=True, related_name="announcements", to="academic.program"
                    ),
                ),
            ],
            options={
                "db_table": "announcements",
                "ordering": ["-is_pinned", "-published_at"],
            },
        ),
        migrations.CreateModel(
            name="BulkNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("category", models.CharField(default="general", max_length=20)),
                ("priority", models.CharField(default="NORMAL", max_length=10)),
                (
                    "target_type",
                    models.CharField(
                        choices=[
                            ("all", "All"),
                            ("role", "Role"),
                            ("department", "Department"),
                            ("program", "Program"),
                            ("batch", "Batch"),
                            ("section", "Section"),
                            ("individual", "Individual"),
                        ],
                        default="all",
                        max_length=20,
                    ),
                ),
                ("target_filters", models.JSONField(blank=True, default=dict)),
                (
                    "channels",
                    models.JSONField(
                        default=dict,
                        help_text='{"email": true, "sms": false, "whatsapp": false, "push": true, "in_app": true}',
                    ),
                ),
                ("total_recipients", models.PositiveIntegerField(default=0)),
                ("sent_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("queued", "Queued"),
                            ("sending", "Sending"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="colleges.college",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "notification",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bulk_campaigns",
                        to="notifications.notification",
                    ),
                ),
                (
                    "sent_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bulk_notifications_sent",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "bulk_notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NotificationPreference",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email_enabled", models.BooleanField(default=True)),
                ("sms_enabled", models.BooleanField(default=True)),
                ("whatsapp_enabled", models.BooleanField(default=False)),
                ("push_enabled", models.BooleanField(default=True)),
                ("dnd_start_time", models.TimeField(blank=True, null=True)),
                ("dnd_end_time", models.TimeField(blank=True, null=True)),
                ("category_preferences", models.JSONField(blank=True, default=dict)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_preferences",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification_preferences",
            },
        ),
        migrations.CreateModel(
            name="NotificationTemplate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("fee_due", "Fee Due"),
                            ("attendance_low", "Low Attendance"),
                            ("result_published", "Result Published"),
                            ("certificate_ready", "Certificate Ready"),
                            ("admission_status", "Admission Status"),
                            ("leave_approved", "Leave Approved"),
                            ("exam_schedule", "Exam Schedule"),
                            ("assignment_due", "Assignment Due"),
                            ("complaint_update", "Complaint Update"),
                            ("custom", "Custom"),
                        ],
                        default="custom",
                        max_length=32,
                    ),
                ),
                ("email_subject", models.CharField(blank=True, max_length=255)),
                ("email_body", models.TextField(blank=True)),
                ("sms_body", models.CharField(blank=True, max_length=160)),
                ("whatsapp_body", models.TextField(blank=True)),
                ("push_title", models.CharField(blank=True, max_length=255)),
                ("push_body", models.TextField(blank=True)),
                ("variables", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "college",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_templates",
                        to="colleges.college",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "notification_templates",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="notification",
            name="template",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notifications",
                to="notifications.notificationtemplate",
            ),
        ),
    ]
