# Generated by Django 5.2 on 2026-05-17 19:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colleges', '0001_initial'),
        ('gate', '0001_initial'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GateLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('entry_type', models.CharField(choices=[('ENTRY', 'Entry'), ('EXIT', 'Exit')], max_length=10)),
                ('person_type', models.CharField(choices=[('STUDENT', 'Student'), ('TEACHER', 'Teacher'), ('STAFF', 'Staff'), ('VISITOR', 'Visitor'), ('VENDOR', 'Vendor'), ('OTHER', 'Other')], max_length=10)),
                ('visitor_name', models.CharField(blank=True, max_length=200)),
                ('visitor_phone', models.CharField(blank=True, max_length=15)),
                ('visitor_id_type', models.CharField(blank=True, max_length=50)),
                ('visitor_id_number', models.CharField(blank=True, max_length=100)),
                ('purpose', models.TextField(blank=True)),
                ('vehicle_number', models.CharField(blank=True, max_length=20)),
                ('vehicle_type', models.CharField(blank=True, max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expected_return', models.DateTimeField(blank=True, null=True)),
                ('actual_return', models.DateTimeField(blank=True, null=True)),
                ('gate_number', models.CharField(blank=True, max_length=20)),
                ('verified_by', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.college')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('meeting_with', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitor_meetings', to=settings.AUTH_USER_MODEL)),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_logs', to=settings.AUTH_USER_MODEL)),
                ('security_guard', models.ForeignKey(blank=True, limit_choices_to={'role': 'SECURITY'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_duty_logs', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gate_logs', to='students.student')),
            ],
            options={
                'db_table': 'gate_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.DeleteModel(
            name='GateVisit',
        ),
    ]
