# Generated by Django 5.2 on 2026-05-25 21:24

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("colleges", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Designation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("teaching", "Teaching"),
                            ("non_teaching", "Non-Teaching"),
                            ("administrative", "Administrative"),
                        ],
                        default="teaching",
                        max_length=20,
                    ),
                ),
                (
                    "level",
                    models.PositiveIntegerField(default=0, help_text="Higher = senior"),
                ),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="colleges.college",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "staff_designations",
                "ordering": ["level", "name"],
                "unique_together": {("college", "name")},
            },
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "employee_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, unique=True
                    ),
                ),
                (
                    "staff_type",
                    models.CharField(
                        choices=[
                            ("teaching", "Teaching"),
                            ("non_teaching", "Non-Teaching"),
                            ("contract", "Contract"),
                            ("visiting", "Visiting"),
                            ("guest", "Guest"),
                        ],
                        default="teaching",
                        max_length=20,
                    ),
                ),
                ("date_of_joining", models.DateField()),
                ("date_of_retirement", models.DateField(blank=True, null=True)),
                (
                    "appointment_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular"),
                            ("adhoc", "Ad-hoc"),
                            ("temporary", "Temporary"),
                            ("contractual", "Contractual"),
                            ("part_time", "Part-Time"),
                        ],
                        default="regular",
                        max_length=20,
                    ),
                ),
                (
                    "appointment_order_number",
                    models.CharField(blank=True, max_length=100),
                ),
                ("appointment_order_date", models.DateField(blank=True, null=True)),
                (
                    "appointment_order_file",
                    models.CharField(
                        blank=True, help_text="MinIO object key", max_length=500
                    ),
                ),
                (
                    "highest_qualification",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("phd", "PhD"),
                            ("mphil", "M.Phil"),
                            ("masters", "Masters"),
                            ("bachelors", "Bachelors"),
                            ("diploma", "Diploma"),
                        ],
                        max_length=20,
                    ),
                ),
                ("specialization", models.CharField(blank=True, max_length=200)),
                (
                    "phd_status",
                    models.CharField(
                        choices=[
                            ("completed", "Completed"),
                            ("pursuing", "Pursuing"),
                            ("not_applicable", "Not Applicable"),
                        ],
                        default="not_applicable",
                        max_length=20,
                    ),
                ),
                ("phd_university", models.CharField(blank=True, max_length=200)),
                ("phd_year", models.PositiveIntegerField(blank=True, null=True)),
                ("phd_thesis_title", models.CharField(blank=True, max_length=500)),
                ("net_set_qualified", models.BooleanField(default=False)),
                ("net_set_year", models.PositiveIntegerField(blank=True, null=True)),
                ("net_set_subject", models.CharField(blank=True, max_length=200)),
                ("qualifications", models.JSONField(blank=True, default=list)),
                (
                    "total_experience_years",
                    models.DecimalField(decimal_places=1, default=0, max_digits=4),
                ),
                (
                    "teaching_experience_years",
                    models.DecimalField(decimal_places=1, default=0, max_digits=4),
                ),
                (
                    "industry_experience_years",
                    models.DecimalField(decimal_places=1, default=0, max_digits=4),
                ),
                ("previous_experiences", models.JSONField(blank=True, default=list)),
                ("pay_band", models.CharField(blank=True, max_length=50)),
                (
                    "grade_pay",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "basic_pay",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("bank_name", models.CharField(blank=True, max_length=100)),
                ("bank_account", models.CharField(blank=True, max_length=50)),
                ("bank_ifsc", models.CharField(blank=True, max_length=20)),
                ("pf_number", models.CharField(blank=True, max_length=50)),
                ("esi_number", models.CharField(blank=True, max_length=50)),
                ("uan_number", models.CharField(blank=True, max_length=50)),
                ("pan_number", models.CharField(blank=True, max_length=20)),
                ("google_scholar_id", models.CharField(blank=True, max_length=100)),
                ("scopus_id", models.CharField(blank=True, max_length=100)),
                ("orcid_id", models.CharField(blank=True, max_length=100)),
                ("vidwan_id", models.CharField(blank=True, max_length=100)),
                ("research_interests", models.JSONField(blank=True, default=list)),
                ("resume", models.CharField(blank=True, max_length=500)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("on_leave", "On Leave"),
                            ("deputation", "Deputation"),
                            ("resigned", "Resigned"),
                            ("retired", "Retired"),
                            ("terminated", "Terminated"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=20,
                    ),
                ),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="colleges.college",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_members",
                        to="colleges.department",
                    ),
                ),
                (
                    "designation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_members",
                        to="staff.designation",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        limit_choices_to={"role": "STAFF"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "staff_members",
                "ordering": ["employee_id"],
            },
        ),
        migrations.CreateModel(
            name="StaffServiceBook",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "entry_type",
                    models.CharField(
                        choices=[
                            ("joining", "Joining"),
                            ("promotion", "Promotion"),
                            ("increment", "Increment"),
                            ("transfer", "Transfer"),
                            ("deputation", "Deputation"),
                            ("suspension", "Suspension"),
                            ("reinstatement", "Reinstatement"),
                            ("retirement", "Retirement"),
                        ],
                        max_length=20,
                    ),
                ),
                ("effective_date", models.DateField(db_index=True)),
                ("order_number", models.CharField(blank=True, max_length=100)),
                ("order_date", models.DateField(blank=True, null=True)),
                ("description", models.TextField()),
                (
                    "old_pay",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "new_pay",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "document",
                    models.CharField(
                        blank=True, help_text="MinIO object key", max_length=500
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "new_designation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="new_entries",
                        to="staff.designation",
                    ),
                ),
                (
                    "old_designation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="old_entries",
                        to="staff.designation",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_book_entries",
                        to="staff.staff",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "staff_service_book",
                "ordering": ["-effective_date"],
            },
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["college", "department"], name="staff_membe_college_af8258_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["college", "staff_type"], name="staff_membe_college_f4c8b7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="staff",
            index=models.Index(
                fields=["college", "status"], name="staff_membe_college_0a5003_idx"
            ),
        ),
    ]
