# Generated by Django 5.2 on 2026-05-28 21:02

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Create"),
                            ("read", "Read"),
                            ("update", "Update"),
                            ("delete", "Delete"),
                            ("login", "Login"),
                            ("logout", "Logout"),
                            ("export", "Export"),
                            ("import", "Import"),
                            ("approve", "Approve"),
                            ("reject", "Reject"),
                            ("generate", "Generate"),
                            ("send", "Send"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "module",
                    models.CharField(
                        choices=[
                            ("authentication", "Authentication"),
                            ("users", "Users"),
                            ("institutions", "Institutions"),
                            ("academic", "Academic"),
                            ("colleges", "Colleges"),
                            ("students", "Students"),
                            ("staff", "Staff"),
                            ("teachers", "Teachers"),
                            ("finance", "Finance"),
                            ("certificates", "Certificates"),
                            ("admissions", "Admissions"),
                            ("notifications", "Notifications"),
                            ("governance", "Governance"),
                            ("audit", "Audit"),
                            ("dashboard", "Dashboard"),
                            ("system", "System"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        default="other",
                        max_length=50,
                    ),
                ),
                ("model_name", models.CharField(blank=True, max_length=100)),
                ("object_id", models.UUIDField(blank=True, db_index=True, null=True)),
                ("object_repr", models.CharField(blank=True, max_length=255)),
                ("changes", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "request_method",
                    models.CharField(blank=True, db_index=True, max_length=10),
                ),
                ("request_path", models.CharField(db_index=True, max_length=500)),
                (
                    "response_status",
                    models.PositiveIntegerField(blank=True, db_index=True, null=True),
                ),
                ("duration_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "created_at"],
                        name="audit_logs_user_id_fbfd51_idx",
                    ),
                    models.Index(
                        fields=["module", "created_at"],
                        name="audit_logs_module_cb850a_idx",
                    ),
                    models.Index(
                        fields=["action", "created_at"],
                        name="audit_logs_action_391715_idx",
                    ),
                    models.Index(
                        fields=["request_path", "created_at"],
                        name="audit_logs_request_fff144_idx",
                    ),
                ],
            },
        ),
    ]
