# Generated by Django 5.2 on 2026-05-28 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="auditlog",
            name="request_path",
            field=models.CharField(blank=True, db_index=True, max_length=500),
        ),
    ]
