# Generated by Django 5.2 on 2026-05-23 07:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("academics", "0002_timetable"),
        ("colleges", "0001_initial"),
        ("teachers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyMaterial",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "material_type",
                    models.CharField(
                        choices=[
                            ("PDF", "PDF Document"),
                            ("VIDEO", "Video"),
                            ("IMAGE", "Image"),
                            ("DOCUMENT", "Word/PPT Document"),
                            ("LINK", "External Link"),
                            ("OTHER", "Other"),
                        ],
                        default="PDF",
                        max_length=10,
                    ),
                ),
                ("file_url", models.CharField(blank=True, max_length=500)),
                ("external_link", models.URLField(blank=True)),
                (
                    "file_size",
                    models.PositiveBigIntegerField(
                        default=0, help_text="Size in bytes"
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("semester", models.PositiveIntegerField()),
                ("section", models.CharField(blank=True, max_length=10)),
                (
                    "access_level",
                    models.CharField(
                        choices=[
                            ("ALL", "All Students"),
                            ("DEPARTMENT", "Department Only"),
                            ("BATCH", "Specific Batch/Section"),
                        ],
                        default="ALL",
                        max_length=10,
                    ),
                ),
                ("is_published", models.BooleanField(default=False)),
                ("download_count", models.PositiveIntegerField(default=0)),
                (
                    "tags",
                    models.CharField(
                        blank=True, help_text="Comma-separated tags", max_length=500
                    ),
                ),
                (
                    "college",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="colleges.college",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_materials",
                        to="colleges.department",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_materials",
                        to="academics.subject",
                    ),
                ),
                (
                    "teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="study_materials",
                        to="teachers.teacher",
                    ),
                ),
            ],
            options={
                "db_table": "study_materials",
                "ordering": ["-created_at"],
            },
        ),
    ]
