# Generated by Django 5.2 on 2026-05-21 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_otpverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="signature",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
