# Generated by Django 5.2 on 2026-05-25 17:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("colleges", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("name", models.CharField(max_length=255)),
                ("short_name", models.CharField(blank=True, max_length=50)),
                ("code", models.CharField(db_index=True, max_length=20, unique=True)),
                ("logo", models.CharField(blank=True, max_length=500)),
                ("favicon", models.CharField(blank=True, max_length=500)),
                (
                    "institution_type",
                    models.CharField(
                        choices=[
                            ("university", "University"),
                            ("autonomous", "Autonomous"),
                            ("affiliated", "Affiliated"),
                            ("deemed", "Deemed"),
                        ],
                        default="affiliated",
                        max_length=20,
                    ),
                ),
                (
                    "affiliation_university",
                    models.CharField(blank=True, max_length=255),
                ),
                ("affiliation_number", models.CharField(blank=True, max_length=100)),
                ("aicte_approval_number", models.CharField(blank=True, max_length=100)),
                ("naac_grade", models.CharField(blank=True, max_length=10)),
                ("naac_valid_until", models.DateField(blank=True, null=True)),
                ("nirf_rank", models.PositiveIntegerField(blank=True, null=True)),
                ("nirf_year", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "established_year",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("website_url", models.URLField(blank=True)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("fax", models.CharField(blank=True, max_length=20)),
                ("address_line_1", models.CharField(blank=True, max_length=255)),
                ("address_line_2", models.CharField(blank=True, max_length=255)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("state", models.CharField(blank=True, max_length=100)),
                (
                    "country",
                    models.CharField(blank=True, default="India", max_length=100),
                ),
                ("pincode", models.CharField(blank=True, max_length=10)),
                ("principal_name", models.CharField(blank=True, max_length=200)),
                ("principal_signature", models.CharField(blank=True, max_length=500)),
                ("registrar_name", models.CharField(blank=True, max_length=200)),
                ("registrar_signature", models.CharField(blank=True, max_length=500)),
                ("stamp_image", models.CharField(blank=True, max_length=500)),
                ("gstin", models.CharField(blank=True, max_length=20)),
                ("pan_number", models.CharField(blank=True, max_length=20)),
                ("bank_name", models.CharField(blank=True, max_length=200)),
                ("bank_account", models.CharField(blank=True, max_length=50)),
                ("bank_ifsc", models.CharField(blank=True, max_length=20)),
                (
                    "college",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="institution",
                        to="colleges.college",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "institutions",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="InstitutionSettings",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("academic_year_start_month", models.PositiveIntegerField(default=6)),
                (
                    "attendance_minimum_percentage",
                    models.DecimalField(decimal_places=2, default=75, max_digits=5),
                ),
                (
                    "grading_system",
                    models.CharField(
                        choices=[
                            ("CGPA_10", "CGPA 10"),
                            ("CGPA_4", "CGPA 4"),
                            ("percentage", "Percentage"),
                            ("grade", "Grade"),
                        ],
                        default="CGPA_10",
                        max_length=20,
                    ),
                ),
                (
                    "result_display_mode",
                    models.CharField(
                        choices=[
                            ("cgpa", "CGPA"),
                            ("percentage", "Percentage"),
                            ("both", "Both"),
                        ],
                        default="cgpa",
                        max_length=20,
                    ),
                ),
                (
                    "fee_late_fine_per_day",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("fee_due_reminder_days", models.JSONField(blank=True, default=list)),
                ("sms_enabled", models.BooleanField(default=False)),
                ("whatsapp_enabled", models.BooleanField(default=False)),
                ("email_enabled", models.BooleanField(default=True)),
                ("sms_api_key", models.CharField(blank=True, max_length=255)),
                ("whatsapp_api_key", models.CharField(blank=True, max_length=255)),
                ("certificate_qr_enabled", models.BooleanField(default=True)),
                ("certificate_blockchain_enabled", models.BooleanField(default=False)),
                (
                    "enrollment_number_format",
                    models.CharField(default="{year}-{dept}-{seq:04d}", max_length=100),
                ),
                (
                    "receipt_number_format",
                    models.CharField(default="RCP-{year}-{seq:06d}", max_length=100),
                ),
                ("timezone", models.CharField(default="Asia/Kolkata", max_length=50)),
                ("date_format", models.CharField(default="DD/MM/YYYY", max_length=20)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "institution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="settings",
                        to="institutions.institution",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "institution_settings",
            },
        ),
    ]
