# Generated by Django 5.2 on 2026-05-17 19:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colleges', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('enrollment_number', models.CharField(db_index=True, max_length=50)),
                ('roll_number', models.CharField(db_index=True, max_length=50)),
                ('semester', models.PositiveIntegerField(default=1)),
                ('section', models.CharField(default='A', max_length=10)),
                ('batch_year', models.PositiveIntegerField()),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('nationality', models.CharField(default='Indian', max_length=50)),
                ('religion', models.CharField(blank=True, max_length=50)),
                ('category', models.CharField(blank=True, max_length=50)),
                ('address', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('emergency_contact', models.CharField(max_length=15)),
                ('emergency_contact_name', models.CharField(max_length=200)),
                ('admission_date', models.DateField()),
                ('admission_type', models.CharField(choices=[('REGULAR', 'Regular'), ('LATERAL', 'Lateral Entry'), ('TRANSFER', 'Transfer')], default='REGULAR', max_length=20)),
                ('previous_education', models.TextField(blank=True)),
                ('previous_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('photo', models.CharField(blank=True, max_length=500)),
                ('id_card', models.CharField(blank=True, max_length=500)),
                ('documents', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('graduation_date', models.DateField(blank=True, null=True)),
                ('academic_year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='colleges.academicyear')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='colleges.branch')),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.college')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='colleges.department')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'students',
                'ordering': ['-created_at'],
                'unique_together': {('college', 'enrollment_number'), ('college', 'roll_number')},
            },
        ),
        migrations.CreateModel(
            name='StudentDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('document_type', models.CharField(choices=[('PHOTO', 'Photo'), ('SIGNATURE', 'Signature'), ('AADHAAR', 'Aadhaar Card'), ('MARKSHEET_10TH', '10th Marksheet'), ('MARKSHEET_12TH', '12th Marksheet'), ('TC', 'Transfer Certificate'), ('CASTE_CERTIFICATE', 'Caste Certificate'), ('INCOME_CERTIFICATE', 'Income Certificate'), ('DOMICILE', 'Domicile Certificate'), ('OTHER', 'Other')], max_length=50)),
                ('file_url', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=255)),
                ('file_size', models.PositiveIntegerField()),
                ('mime_type', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='colleges.college')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_documents', to='students.student')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'student_documents',
                'ordering': ['-created_at'],
            },
        ),
    ]
