# Generated by Django 5.2 on 2026-05-21 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="signature",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
