# Generated by Django 5.2 on 2026-05-25 20:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0002_add_signature_field"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentDocumentVerification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("photo", "Photo"),
                            ("aadhaar", "Aadhaar Card"),
                            ("ssc_marksheet", "SSC Marksheet"),
                            ("hsc_marksheet", "HSC Marksheet"),
                            ("caste_cert", "Caste Certificate"),
                            ("income_cert", "Income Certificate"),
                            ("domicile", "Domicile Certificate"),
                            ("transfer_cert", "Transfer Certificate"),
                            ("migration_cert", "Migration Certificate"),
                            ("gap_cert", "Gap Certificate"),
                            ("medical_cert", "Medical Certificate"),
                            ("disability_cert", "Disability Certificate"),
                            ("diploma_marksheet", "Diploma Marksheet"),
                            ("graduation_marksheet", "Graduation Marksheet"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("verified", "Verified"),
                            ("rejected", "Rejected"),
                            ("re_upload_requested", "Re-Upload Requested"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=25,
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("remarks", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="document_verifications",
                        to="students.student",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="verified_documents",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "student_document_verifications",
                "ordering": ["student", "document_type"],
                "unique_together": {("student", "document_type")},
            },
        ),
        migrations.CreateModel(
            name="StudentSemesterRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("semester_number", models.PositiveSmallIntegerField()),
                (
                    "academic_year_label",
                    models.CharField(help_text="e.g. 2024-25", max_length=20),
                ),
                (
                    "sgpa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "cgpa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("total_credits_earned", models.PositiveIntegerField(default=0)),
                (
                    "attendance_percentage",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ongoing", "Ongoing"),
                            ("passed", "Passed"),
                            ("failed", "Failed"),
                            ("detained", "Detained"),
                            ("backlog", "Backlog"),
                        ],
                        default="ongoing",
                        max_length=20,
                    ),
                ),
                ("promoted_to_next", models.BooleanField(default=False)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="semester_records",
                        to="students.student",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "student_semester_records",
                "ordering": ["student", "semester_number"],
                "indexes": [
                    models.Index(
                        fields=["student", "status"],
                        name="student_sem_student_4e490b_idx",
                    )
                ],
                "unique_together": {
                    ("student", "semester_number", "academic_year_label")
                },
            },
        ),
    ]
