# Generated by Django 5.2 on 2026-05-26 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_add_semester_record_docverification"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="abc_id",
            field=models.CharField(
                blank=True, help_text="Academic Bank of Credits ID", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="admission_number",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="caste",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="digilocker_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="domicile_state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="hostel_resident",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="identification_mark",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="student",
            name="library_card_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="student",
            name="mother_tongue",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="status_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="status_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="student",
            name="student_status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("detained", "Detained"),
                    ("suspended", "Suspended"),
                    ("rusticated", "Rusticated"),
                    ("dropped_out", "Dropped Out"),
                    ("passout", "Passed Out"),
                    ("alumni", "Alumni"),
                    ("year_back", "Year Back"),
                    ("semester_back", "Semester Back"),
                ],
                db_index=True,
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="sub_category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="transport_user",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="university_roll_number",
            field=models.CharField(
                blank=True, db_index=True, max_length=50, null=True, unique=True
            ),
        ),
    ]
