# Generated by Django 5.2 on 2026-05-27 08:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_add_missing_student_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="mentor",
            field=models.ForeignKey(
                blank=True,
                help_text="Assigned faculty mentor",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mentored_students",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
