# Generated by Django 5.2 on 2026-05-29 04:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0006_student_json_profile_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="abc_id",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="student",
            name="admission_type",
            field=models.CharField(
                choices=[
                    ("REGULAR", "Regular"),
                    ("LATERAL", "Lateral Entry"),
                    ("TRANSFER", "Transfer"),
                    ("MANAGEMENT", "Management"),
                    ("NRI", "NRI"),
                    ("SPORTS", "Sports"),
                    ("CULTURAL", "Cultural"),
                ],
                default="REGULAR",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="education_details",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="SSC/HSC/entrance/diploma/graduation history and document keys",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="family_details",
            field=models.JSONField(
                blank=True,
                default=dict,
                help_text="father/mother/guardian names, phones, occupations, income",
            ),
        ),
        migrations.AlterField(
            model_name="student",
            name="mentor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="mentored_students",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
